version: '3.3'

services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=store
            - POSTGRES_USER=run
            - POSTGRES_PASSWORD=adm123
        ports:
            - 5432:5432
        volumes:
            - ./db/data/postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=run@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - 5050:80

    mysql:
        image: mysql:5
        environment:
            - MYSQL_DATABASE=store
            - MYSQL_USER=
            - MYSQL_ROOT_PASSWORD=adm123
            - MYSQL_PORT=3306
        ports:
            - "3306:3306"
        volumes:
            - ./db/data/mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=adm123
            - PMA_HOST=mysql
        ports:
            - 8080:80
